name: CI-CD-Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my-ci-part:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone Repository 
        uses: actions/checkout@v3

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
        with:
          source: 'index.html'
          target: '/var/www/html/'
